language: python
python:
  - 2.7
  - 3.2
install:
  - sudo apt-get update -qq
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install python-numpy python-matplotlib; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then sudo apt-get install python3-numpy; fi
before_script:
  - python setup.py build
  - python setup.py install
script:
  - prody test -l full
