language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install nose unittest2 numpy matplotlib; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install python-nose python-matplotlib; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then sudo apt-get install python3-nose python3-dev python3-numpy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then pip install matplotlib; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then sudo apt-get install python3-nose; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then pip install numpy matplotlib; fi
install:
  - python setup.py build install
script:
  - prody test -l full -v 5
