language: python
python:
  - 2.7
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
install:
  - sudo apt-get update -qq
  - if [[ $TRAVIS_PYTHON_VERSION == "2.7" ]]; then sudo apt-get install python-matplotlib; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.2" ]]; then sudo apt-get install python3-dev python3-numpy; fi
  - if [[ $TRAVIS_PYTHON_VERSION == "3.3" ]]; then sudo pip install numpy==1.7.1 matplotlib==1.3; fi
  - python setup.py build install
script:
  - prody test -l full
