language: python
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-nose python3-nose python-numpy python3-numpy python-scipy python3-scipy python-matplotlib python3-matplotlib
python:
  - "2.7"
  - "3.2"
script:
  - ./scripts/prody test