language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
virtualenv:
  system_site_packages: true
before_install:
  - uname -a
  - free -m
  - df -h
  - ulimit -a
  - sudo apt-get update -qq
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install nose
  - pip install numpy
  - pip install matplotlib
  - if [[ $TRAVIS_PYTHON_VERSION == "2.6" ]]; then pip install unittest2; fi
install:
  - python setup.py build install
script:
  - prody test -o 0.1 -v 5
